In [1]:
# Useful starting lines
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
%load_ext autoreload
%autoreload 2

In [2]:
from proj1_helpers import *
DATA_TRAIN_PATH = 'train.csv' # TODO: download train data and supply path here 
y, tX, ids = load_csv_data(DATA_TRAIN_PATH)

In [3]:
#replace values -999.0 by the mean of each columns
(a,b)=np.shape(tX)
for i in range(b):
    ind=np.where(tX[:,i]==-999)
    tX_del=np.delete(tX[:,i],ind)
    mean=np.mean(tX_del)
    tX[ind,i]=mean

In [4]:
from standardize import standardize
tX=standardize(tX)

In [5]:
tX=np.c_[tX,np.ones(len(y))]

In [9]:
from logistic import *
gamma=0.01
max_iter=100
threshold = 1e-8
initial_w=-np.zeros((31,))
w,loss=logistic_regression_gradient_descent(y, tX,gamma,max_iter,threshold,initial_w)

[0.5 0.5 0.5 ... 0.5 0.5 0.5]
[ 0.5 -1.5 -1.5 ...  0.5 -1.5 -1.5]
268111.77384252247
-308478.18624461186
Current iteration=0, loss=-308478.18624461186
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
167836.85480572228
-267532.16886276763
[0.00000000e+000 0.00000000e+000 0.00000000e+000 ... 0.00000000e+000
 1.53061066e-219 0.00000000e+000]
[ 1. -1. -1. ...  1. -1. -1.]
138114.99301886847
-262760.40636115486
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135815.8501652313
-263133.43064220686
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135532.0685124348
-263131.64229449874
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135421.30858510328
-263155.35656722623
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135381.53687352707
-263182.6243827496
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135363.36878588054
-263208.3659485578
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135351.4696210831
-263211.0389350636
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1.

[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64666272973
-263268.85620974505
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.6462660028
-263268.76347018953
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64595310652
-263268.6751968715
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64567361117
-263268.60260607756
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64541641963
-263268.5499020526
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.6452145721
-263268.5325719245
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64505908106
-263268.5391441572
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64488683423
-263268.5533730667
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64455041822
-263268.59404390975
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64349122424
-263268.84907163616
[0. 0. 0. ... 0. 0. 0.]
[ 1. -1. -1. ...  1. -1. -1.]
135326.64160961518
-263

In [ ]:
w
loss

In [ ]:
1/(1+np.log(np.exp(10**6)))